import PDFDocument from "pdfkit";
import fs from "fs";
import { prisma } from "./prisma";
import { writePrivate } from "./storage";
import { decrypt } from "./crypto";

// pdfkit's built-in fonts have no ₦ glyph, so PDFs say "NGN".
const ngn = (k: number) => "NGN " + (k / 100).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const day = (d: Date) => d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
const PERIOD = { MONTHLY: "month", QUARTERLY: "quarter (3 months)", BIANNUAL: "6 months", ANNUAL: "year" } as const;

function render(build: (d: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const d = new PDFDocument({ size: "A4", margin: 56 }), chunks: Buffer[] = [];
    d.on("data", (c) => chunks.push(c)); d.on("end", () => resolve(Buffer.concat(chunks))); d.on("error", reject);
    build(d); d.end();
  });
}
const row = (d: PDFKit.PDFDocument, k: string, v: string) => { // fixed two-column layout so long values never wrap under the label
  const y = d.y;
  d.font("Helvetica").fontSize(10).fillColor("#555").text(k, 56, y, { width: 170 }); const y1 = d.y;
  d.font("Helvetica-Bold").fillColor("#000").text(v, 230, y, { width: 310 }); d.y = Math.max(y1, d.y) + 3; d.x = 56;
};

async function load(tenancyId: string) {
  const t = await prisma.tenancy.findUnique({ where: { id: tenancyId }, include: {
    tenant: { select: { fullName: true } },
    unit: { include: { property: { include: { location: { select: { name: true } }, owner: { select: { fullName: true } }, parent: { select: { name: true } } } } } } } });
  if (!t) return null;
  const token = t.tokenId ? await prisma.paymentToken.findUnique({ where: { id: t.tokenId } }) : null;
  const confirmer = token?.confirmedById ? await prisma.user.findUnique({ where: { id: token.confirmedById }, select: { fullName: true } }) : null;
  return { t, token, confirmer };
}

export async function agreementBuffer(tenancyId: string) {
  const x = await load(tenancyId); if (!x) return null;
  const { t, token, confirmer } = x, p = t.unit.property, total = token ? token.rentKobo + token.cautionKobo + token.serviceChargeKobo : t.rentKobo;
  return render((d) => {
    d.font("Helvetica-Bold").fontSize(18).text("TENANCY AGREEMENT", { align: "center" }).moveDown(0.3);
    d.font("Helvetica").fontSize(9).fillColor("#666").text("Generated by the platform from the confirmed rental. Reference " + (token?.code ?? t.id), { align: "center" }).moveDown(1.2);
    d.fillColor("#000").font("Helvetica-Bold").fontSize(12).text("1. Parties").moveDown(0.3);
    row(d, "Landlord:", p.owner.fullName); row(d, "Tenant:", t.tenant.fullName);
    d.moveDown(0.8).font("Helvetica-Bold").fontSize(12).text("2. The premises").moveDown(0.3);
    row(d, "Unit:", t.unit.title); row(d, "Property:", p.name + (p.parent ? " (" + p.parent.name + ")" : "")); row(d, "Address:", `${p.address}, ${p.location.name}`);
    d.moveDown(0.8).font("Helvetica-Bold").fontSize(12).text("3. Term and rent").moveDown(0.3);
    row(d, "Starts:", day(t.startsAt)); row(d, "Ends:", day(t.endsAt));
    row(d, "Rent:", `${ngn(t.rentKobo)} per ${PERIOD[t.payDuration]}`);
    if (token) { row(d, "Caution (security) deposit:", ngn(token.cautionKobo)); row(d, "Service charge:", ngn(token.serviceChargeKobo)); }
    row(d, "Total paid on signing:", ngn(total));
    d.moveDown(0.8).font("Helvetica-Bold").fontSize(12).text("4. Payment").moveDown(0.3);
    d.font("Helvetica").fontSize(10).text(token
      ? `The tenant paid ${ngn(total)} by bank transfer directly to ${token.payAccountName} (${token.payBankName}, account ending ${token.payAccountNumberEnc ? decrypt(token.payAccountNumberEnc).slice(-4) : "----"}). Receipt of this payment was confirmed on the platform by ${confirmer?.fullName ?? "the landlord's representative"} on ${token.confirmedAt ? day(token.confirmedAt) : "-"}. The platform did not receive or hold any of this money.`
      : "Payment details are recorded on the platform.");
    d.moveDown(0.8).font("Helvetica-Bold").fontSize(12).text("5. Terms").moveDown(0.3);
    d.font("Helvetica").fontSize(10).list([
      "The tenant will use the premises as a residence (or the agreed use) and will not sublet without the landlord's written consent.",
      "The tenant will pay rent on or before the due date and keep the premises in good condition, fair wear and tear excepted.",
      "The caution deposit is held by the landlord and returned at the end of the tenancy after deducting only proven damage or unpaid sums.",
      "Repairs and faults are reported through the platform's maintenance tickets so both sides have a record.",
      "Either party must give notice before the tenancy ends or is not renewed, as required by the tenancy law of the state where the premises are located.",
      "Any rent increase or change to these terms must be agreed in writing by both parties.",
    ], { bulletRadius: 1.5, textIndent: 10 });
    d.moveDown(1.2).font("Helvetica-Oblique").fontSize(8.5).fillColor("#666").text("This is a standard summary agreement generated by the platform. The parties may agree additional written terms. It is not legal advice.");
  });
}

export async function receiptBuffer(tokenId: string) {
  const t = await prisma.paymentToken.findUnique({ where: { id: tokenId }, include: {
    tenant: { select: { fullName: true } }, unit: { include: { property: { include: { owner: { select: { fullName: true } } } } } } } });
  if (!t || t.status !== "PAID") return null;
  const total = t.rentKobo + t.cautionKobo + t.serviceChargeKobo + t.platformFeeKobo;
  return render((d) => {
    d.font("Helvetica-Bold").fontSize(18).text("PAYMENT RECEIPT", { align: "center" }).moveDown(1);
    row(d, "Receipt no:", t.code ?? t.id); row(d, "Date confirmed:", t.confirmedAt ? day(t.confirmedAt) : "-");
    row(d, "Received from:", t.tenant.fullName); row(d, "Landlord:", t.unit.property.owner.fullName);
    row(d, "For:", (t.kind === "RENEWAL" ? "Renewal of " : "") + t.unit.title);
    d.moveDown(0.8);
    row(d, "Rent:", ngn(t.rentKobo)); if (t.cautionKobo) row(d, "Caution deposit:", ngn(t.cautionKobo)); if (t.serviceChargeKobo) row(d, "Service charge:", ngn(t.serviceChargeKobo));
    d.moveDown(0.4); row(d, "TOTAL:", ngn(total));
    d.moveDown(0.8); row(d, "Paid to:", `${t.payAccountName} (${t.payBankName})`); row(d, "Method:", "Bank transfer, paid directly to the landlord or manager");
    d.moveDown(1.2).font("Helvetica-Oblique").fontSize(8.5).fillColor("#666").text("Receipt of this payment was confirmed on the platform by the person who received it. The platform does not hold or process rent.");
  });
}

// Saved once at confirmation so the agreement is a fixed record; regenerated on demand if the file is ever missing.
export async function writeAgreement(tenancyId: string) {
  const buf = await agreementBuffer(tenancyId); if (!buf) return null;
  const key = `agreement-${tenancyId}.pdf`;
  await writePrivate(key, buf);
  await prisma.tenancy.update({ where: { id: tenancyId }, data: { agreementUrl: key } });
  return buf;
}
